// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChoNVbXkbJqCpWeu1odPx3LlAfOn7bGVk',
    appId: '1:51033512310:web:eabd65010fc4536f2e8257',
    messagingSenderId: '51033512310',
    projectId: 'test-flutter-b0178',
    authDomain: 'test-flutter-b0178.firebaseapp.com',
    storageBucket: 'test-flutter-b0178.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_oX9ScpKOS8TAlSxqXAKqyAYO6i8h4lU',
    appId: '1:51033512310:android:f3868ec17eb0fb952e8257',
    messagingSenderId: '51033512310',
    projectId: 'test-flutter-b0178',
    storageBucket: 'test-flutter-b0178.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCOhaU46mApuYg-WjZYoxwf3jvqufUcp4o',
    appId: '1:51033512310:ios:325aad2d18b9675a2e8257',
    messagingSenderId: '51033512310',
    projectId: 'test-flutter-b0178',
    storageBucket: 'test-flutter-b0178.appspot.com',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCOhaU46mApuYg-WjZYoxwf3jvqufUcp4o',
    appId: '1:51033512310:ios:325aad2d18b9675a2e8257',
    messagingSenderId: '51033512310',
    projectId: 'test-flutter-b0178',
    storageBucket: 'test-flutter-b0178.appspot.com',
    iosBundleId: 'com.example.testFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyChoNVbXkbJqCpWeu1odPx3LlAfOn7bGVk',
    appId: '1:51033512310:web:c85503f1d719ce692e8257',
    messagingSenderId: '51033512310',
    projectId: 'test-flutter-b0178',
    authDomain: 'test-flutter-b0178.firebaseapp.com',
    storageBucket: 'test-flutter-b0178.appspot.com',
  );
}
